export const metricLabels: Record<string, { label: string; description: string }> = {
  n: { label: "n", description: "Total rows considered" },
  nonMissingCount: { label: "Non-missing", description: "Rows with a numeric response" },
  missingCount: { label: "Missing", description: "Rows without a usable response" },
  mean: { label: "Mean", description: "Average of responses" },
  median: { label: "Median", description: "50th percentile" },
  mode: { label: "Mode", description: "Most frequent value(s), when meaningful" },
  geometricMean: { label: "Geometric mean", description: "Only for strictly positive values" },
  trimmedMean: { label: "Trimmed mean", description: "Mean after light trimming" },
  sd: { label: "SD", description: "Standard deviation (spread)" },
  variance: { label: "Variance", description: "Variance of responses" },
  sem: { label: "SEM", description: "Precision of the mean (not spread)" },
  cvPercent: { label: "CV%", description: "Coefficient of variation" },
  min: { label: "Min", description: "Minimum" },
  max: { label: "Max", description: "Maximum" },
  range: { label: "Range", description: "Max - Min" },
  q1: { label: "Q1", description: "25th percentile" },
  q3: { label: "Q3", description: "75th percentile" },
  iqr: { label: "IQR", description: "Interquartile range" },
  mad: { label: "MAD", description: "Median absolute deviation" },
  skewness: { label: "Skewness", description: "Asymmetry" },
  kurtosis: { label: "Kurtosis", description: "Tail weight (Fisher)" },
  ci95: { label: "95% CI", description: "Confidence interval for the mean (if valid)" },
};
